language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
branches:
  only:
    - master
    - feature/angular
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a534fbf2d70b49f104e6
    on_success: change
    on_failure: always
    on_start: never
