/**
 * Copyright 2017 Cinovo AG<br>
 * <br>
 *
 * @author psigloch
 */
export enum Mode {
  EDIT,
  NEW
}

export enum ServiceState {
  STARTING,
  STARTED,
  IN_SERVICE,
  STOPPING,
  STOPPED,
  RESTARTING_STOPPING,
  RESTARTING_STARTING
}

export enum Role {
  VIEW_HOST = 'VIEW_HOST',
  EDIT_HOST = 'EDIT_HOST',

  VIEW_TEMPLATE = 'VIEW_TEMPLATE',
  EDIT_TEMPLATE = 'EDIT_TEMPLATE',

  VIEW_CONFIGVALUES = 'VIEW_CONFIGVALUES',
  EDIT_CONFIGVALUES = 'EDIT_CONFIGVALUES',

  VIEW_USERS = 'VIEW_USERS',
  EDIT_USERS = 'EDIT_USERS',

  VIEW_SSH = 'VIEW_SSH',
  EDIT_SSH = 'EDIT_SSH',

  VIEW_CONFIGURATIONS = 'VIEW_CONFIGURATIONS',
  EDIT_CONFIGURATIONS = 'EDIT_CONFIGURATIONS'
}
