name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      with:
        node-version: '14.x'
        cache: npm
        cache-dependency-path: 'src/main/webapp/package-lock.json'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
