name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Use qodana-backend config'
        run: cp qodana-backend.yaml qodana.yaml
      - name: 'Qodana Backend Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          artifact-name: qodana-backend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Use qodana-frontend config'
        run: cp qodana-frontend.yaml qodana.yaml
      - name: 'Qodana Frontend Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          artifact-name: qodana-frontend
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_FRONTEND }}
